[package]
name = "darkmode-pdf"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
image = "0.24"
kurbo = "0.11"
peniko = "0.4"
printpdf = { version = "0.7", features = ["embedded_images"] }
pulldown-cmark = "0.10"
syntect = "5.2"
time = "0.3"
ttf-parser = "0.25"

[dev-dependencies]
tempfile = "3.10"
